// Angular/DITSTEK/src/app/modules/login/login.component.ts
import { ApiService } from "./../../shared/services/api.service";
import { APIURLS } from "./../../config/api_url";
import { Component, OnInit } from "@angular/core";
import { ViewChild } from "@angular/core";
import { NgForm } from "@angular/forms";
import { ToastrManager } from "ng6-toastr-notifications";
import { Router } from "@angular/router";
@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.css"],
  providers: [ApiService]
})
export class LoginComponent implements OnInit {
  @ViewChild("myloader")
  input;

  records: Array<any>;
  constructor(
    private _ApiService: ApiService,
    private toastr: ToastrManager,
    private router: Router
  ) {}

  ngOnInit() {
    const body = document.getElementsByTagName("body")[0];
    body.classList.add("login-page");
  }
  onsubmit(formdata) {
    this._ApiService
      .post(APIURLS.LOG_IN_API, formdata)
      .subscribe((response: any) => {
        this.records = response;
        if (response.Success == true) {
          this.toastr.successToastr("", "Successfully logged In");
          localStorage.setItem("loginDetails", JSON.stringify(response));
          this.router.navigate(["/dashboard"]);
        } else {
          this.toastr.errorToastr("Error", response.Message, { maxShown: 1 });
        }
      });
  }
}

<div class="login-box">
  <div class="logo">
      <a href="javascript:void(0);">
          <b>DITS</b>
      </a>
      <small>Please sign in to continue</small>
  </div>
  <div class="card">
      <div class="body">
          <form #loginForm="ngForm" (ngSubmit)="onsubmit(loginForm.value)">
              <div class="msg">Sign in to start your session</div>

              <div class="input-group display font" [class.has-error]="usernameControl.invalid && usernameControl.touched">
                      <span class="input-group-addon">
                          <i class="material-icons">person</i>
                      </span>
                      <div class="form-line font">
                          <input #usernameControl="ngModel" [(ngModel)]="username" type="text" class="form-control font" name="username" placeholder="Username"
                              required >
                      </div>
                      <div>
                      <span class="error input-group" *ngIf="usernameControl.invalid && usernameControl.touched">Username is required</span>
                  </div>
                  </div>
              


              <div class="input-group display" [class.has-error]="passwordControl.invalid && passwordControl.touched">
                  <span class="input-group-addon">
                      <i class="material-icons">lock</i>
                  </span>
                  <div class="form-line">
                      <input #passwordControl="ngModel" [(ngModel)]="password" type="password" class="form-control font" name="password" placeholder="Password"
                          required>
                  </div>
                  <span class="error" *ngIf="passwordControl.invalid && passwordControl.touched">Password is required</span>
              </div>

              <div class="row">
                  <div class="col-xs-8 p-t-5">
                      <input type="checkbox" name="rememberme" id="rememberme" class="filled-in chk-col-pink">
                      <label for="rememberme">Remember Me</label>
                  </div>
                  <div class="col-xs-4">
                      <button class="btn btn-block bg-pink waves-effect" [disabled]="loginForm.invalid" type="submit">SIGN IN</button>
                  </div>
              </div>
              <div class="row m-t-15 m-b--20">
                  <div class="col-xs-6">
                      <a [routerLink]="['/signup']">Register Now!</a>
                  </div>
                  <div class="col-xs-6 align-right">
                      <a [routerLink]="['/forgot-password']">Forgot Password?</a>
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>

// React/app/src/components/auth/login.jsx
import React, { Component } from "react";
import { Redirect } from "react-router-dom";
import AjaxHelper from "../common/ajaxHelper";
import BlockUi from "react-block-ui";
import "react-block-ui/style.css";
import validator from "validator";
import classNames from "classnames";

class Login extends Component {
  constructor(props) {
    super(props);
    this.handleRedirect = this.handleRedirect.bind(this);
  }

  formDefaults = {
    username: { value: "", isValid: true, message: "" },
    password: { value: "", isValid: true, message: "" },
    blocking: false
  };

  state = {
    ...this.formDefaults
  };

  handleChange = e => {
    this.setState({
      [e.target.name]: { value: e.target.value, isValid: true, message: "" }
    });
  };

  handleRedirect = () => {
    this.props.history.push(`/Home`);
  };

  onRegister = event => {
    event.preventDefault();
    this.props.history.push(`/Register`);
  };

  onForgot = event => {
    event.preventDefault();
    this.props.history.push(`/ForgotPassword`);
  };

  submitOnAxios = e => {
    e.preventDefault();
    if (this.formIsValid()) {
      this.setState({ blocking: true });
      var data = {
          UserName: this.state.username.value,
          Password: this.state.password.value
        },
        url = "http://localhost:64519/CommonAPI/UserLogin";
      let myajaxresult = AjaxHelper(url, data)
        .then(res => {
          this.setState({ blocking: false });

          if (res.Success) {
            localStorage.setItem("Name", res.Name);
            localStorage.setItem("BasicInfoId", res.UserBasicInformationId);
            localStorage.setItem("Email", res.Email);
            this.handleRedirect();
          } else {
            let element = document.getElementById("errorBlock");
            element.classList.remove("hide");
            alert(res.Message);
          }
        })
        .catch(error => {
          this.setState({ blocking: false });
          alert(error + "catch block executed");
        });
    }
  };

  formIsValid = () => {
    let username = this.state.username;
    let password = this.state.password;
    let isGood = true;

    if (validator.isEmpty(username.value)) {
      username.isValid = false;
      username.message = "Please enter user name";
      isGood = false;
    }
    if (validator.isEmpty(password.value)) {
      password.isValid = false;
      password.message = "Please enter password";
      isGood = false;
    }

    if (!isGood) {
      this.setState({
        username,
        password
      });
    }
    return isGood;
  };

  render() {
    document.body.classList.add("login-page");
    const { username, password } = this.state;
    const usernameGroupClass = classNames("erroralert", {
      error: !username.isValid
    });
    const passwordGroupClass = classNames("erroralert", {
      error: !password.isValid
    });
    return (
      <div>
        <BlockUi tag="div" blocking={this.state.blocking} />

        <div className="login-box">
          <div className="logo">
            <a>
              <b>DITS</b>
            </a>
            <small />
          </div>
          <div className="card">
            <div className="body">
              <form id="sign_in" method="POST" onSubmit={this.submitOnAxios}>
                <div className="msg">Sign in to start your session</div>
                <div
                  id="errorBlock"
                  className="alert bg-pink hide"
                  role="alert"
                >
                  <strong>Oh snap!</strong>
                  &nbsp;Check login details and try again.
                </div>
                <div className="form-group">
                  <span className="input-group-addon">
                    <i className="material-icons">person</i>
                  </span>
                  <div className="form-line">
                    <input
                      type="text"
                      className="form-control"
                      name="username"
                      placeholder="Username"
                      value={this.state.username.value}
                      onChange={e => this.handleChange(e)}
                    />
                  </div>
                  <label className={usernameGroupClass}>
                    {username.message}
                  </label>
                </div>
                <div className="form-group">
                  <span className="input-group-addon">
                    <i className="material-icons">lock</i>
                  </span>
                  <div className="form-line">
                    <input
                      type="password"
                      className="form-control"
                      name="password"
                      placeholder="Password"
                      value={this.state.password.value}
                      onChange={e => this.handleChange(e)}
                    />
                  </div>
                  <label className={passwordGroupClass}>
                    {password.message}
                  </label>
                </div>
                <div className="row">
                  <div className="col-xs-8 p-t-5">
                    <input
                      type="checkbox"
                      name="rememberme"
                      id="rememberme"
                      className="filled-in chk-col-pink"
                    />
                    <label htmlFor="rememberme">Remember Me</label>
                  </div>
                  <div className="col-xs-4">
                    <button
                      className="btn btn-block bg-pink waves-effect"
                      type="submit"
                    >
                      SIGN IN
                    </button>
                  </div>
                </div>
                <div className="row m-t-15 m-b--20">
                  <div className="col-xs-6">
                    <a onClick={event => this.onRegister(event)}>
                      Register Now!
                    </a>
                  </div>
                  <div className="col-xs-6 align-right">
                    <a onClick={event => this.onForgot(event)}>
                      Forgot Password?
                    </a>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Login;
