// React/app/src/components/common/sidebar.jsx
import React, { Component } from 'react';
import { Redirect } from "react-router-dom";
import { Link, NavLink } from 'react-router-dom';

class Sidebar extends Component {
    // constructor(props) {
    //     super(props);
    //     this.onSignout = this.onSignout.bind(this);
    //   }
    // handleRedirect = () => {
    //    window.location.href="/Home/Profile";
    // }
    // onSignout = event =>{
    //     event.preventDefault();
    //     this.props.history.push(`/Login`);
    // }

    render() {
        return (  
            <aside id="leftsidebar" className="sidebar">
            <div className="user-info">
                <div className="image">
                    <img src={require('../../assets/images/user.png')} width="48" height="48" alt="User" />
                </div>
                <div className="info-container">
                    <div className="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{localStorage.getItem('Name')}</div>
                    <div className="email">{localStorage.getItem('Email')}</div>
                    <div className="btn-group user-helper-dropdown">
                        <i className="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul className="dropdown-menu pull-left">
                            <li><NavLink to="/Home/Profile"><i className="material-icons">person</i>Profile</NavLink></li>
                            <li role="separator" className="divider"></li>
                            <li><Link to='/Home'><i className="material-icons">group</i>Followers</Link></li>
                            <li><Link to='/Home'><i className="material-icons">shopping_cart</i>Sales</Link></li>
                            <li><Link to='/Home'><i className="material-icons">favorite</i>Likes</Link></li>
                            <li role="separator" className="divider"></li>
                            <li><NavLink to="/Login"><i className="material-icons">input</i>Sign Out</NavLink></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div className="menu">
                <ul className="list">
                    <li className="header">MAIN NAVIGATION</li>
                    <li className="active">
                        <Link to='/Home'>
                            <i className="material-icons">home</i>
                            <span>Home</span>
                        </Link>
                    </li>
                   
                </ul>
            </div>
        </aside>
        );
    }
}
 
export default Sidebar;

// Angular/DITSTEK/src/app/shared/components/sidebar/sidebar.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";

@Component({
  selector: "app-sidebar",
  templateUrl: "./sidebar.component.html",
  styleUrls: ["./sidebar.component.css"]
})
export class SidebarComponent implements OnInit {
  records: any = [];

  constructor(private router: Router) {}

  ngOnInit() {
    this.records = JSON.parse(localStorage.getItem("loginDetails"));
  }
  signOut() {
    debugger;
    localStorage.removeItem("loginDetails");
    this.router.navigate(["/login"]);
  }
}

<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="image">
                <img src="./assets/images/user.png" width="48" height="48" alt="User" />
            </div>
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{records.UserDetail.Username}}</div>
                <div class="email">{{records.UserDetail.Email}}</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:void(0)" [routerLink]="['/profile']">
                                <i class="material-icons">person</i>Profile</a>
                        </li>
                        <li role="separator" class="divider"></li>

                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="javascript:void(0)" (click)="signOut()">
                                <i class="material-icons">input</i>Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MAIN NAVIGATION</li>
                <li class="active">
                    <a href="index.html">
                        <i class="material-icons">home</i>
                        <span>Home</span>
                    </a>
                </li>

                <li class="active">
                    <a href="index.html" [routerLink]="['/task']">
                        <i class="material-icons">details</i>
                        <span>Task</span>
                    </a>
                </li>

                <li class="active">
                    <a href="index.html">
                        <i class="material-icons">settings</i>
                        <span>Settings</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; 2018
                <a href="javascript:void(0);">DITS</a>.
            </div>
            <div class="version">
            </div>
        </div>
        <!-- #Footer -->
    </aside>

</section>
